TRACK_BANK_NONE = 0
TRACK_BANK_LEFT = 2
TRACK_BANK_RIGHT = 4
TRACK_BANK_UPSIDE_DOWN = 15
TRACK_SLOPE_NONE = 0
TRACK_SLOPE_UP_25 = 2
TRACK_SLOPE_UP_60 = 4
TRACK_SLOPE_DOWN_25 = 6
TRACK_SLOPE_DOWN_60 = 8
TRACK_SLOPE_UP_90 = 10
TRACK_SLOPE_DOWN_90 = 18

TRACK_VANGLE_TOWER = 10
TRACK_VANGLE_REVERSE_FREEFALL = 10

TRACK_NONE = 0

TRACK_FLAT = 0
TRACK_STRAIGHT =1
TRACK_STATION_END=2
TRACK_LIFT_HILL=3
TRACK_LIFT_HILL_STEEP=4
TRACK_LIFT_HILL_CURVE=5
TRACK_FLAT_ROLL_BANKING=6
TRACK_VERTICAL_LOOP=7
TRACK_SLOPE=8
TRACK_SLOPE_STEEP_DOWN=9
TRACK_SLOPE_LONG=10
TRACK_SLOPE_CURVE=11
TRACK_SLOPE_CURVE_STEEP=12
TRACK_S_BEND=13
TRACK_CURVE_VERY_SMALL=14
TRACK_CURVE_SMALL=15
TRACK_CURVE=16
TRACK_TWIST=17
TRACK_HALF_LOOP=18
TRACK_CORKSCREW=19
TRACK_TOWER_BASE=20
TRACK_HELIX_SMALL=21
TRACK_HELIX_LARGE=22
TRACK_HELIX_LARGE_UNBANKED=23
TRACK_BRAKES=24
TRACK_25=25
TRACK_ON_RIDE_PHOTO=26
TRACK_WATER_SPLASH=27
TRACK_SLOPE_VERTICAL=28
TRACK_BARREL_ROLL=29
TRACK_POWERED_LIFT=30
TRACK_HALF_LOOP_LARGE=31
TRACK_SLOPE_CURVE_BANKED=32
TRACK_LOG_FLUME_REVERSER=33
TRACK_HEARTLINE_ROLL=34
TRACK_REVERSER=35
TRACK_REVERSE_FREEFALL=36
TRACK_SLOPE_TO_FLAT=37
TRACK_BLOCK_BRAKES=38
TRACK_SLOPE_ROLL_BANKING=39
TRACK_SLOPE_STEEP_LONG=40
TRACK_CURVE_VERTICAL=41
TRACK_42=42
TRACK_LIFT_HILL_CABLE=43
TRACK_LIFT_HILL_CURVED=44
TRACK_QUARTER_LOOP=45
TRACK_SPINNING_TUNNEL=46
TRACK_BOOSTER=47
TRACK_INLINE_TWIST_UNINVERTED=48
TRACK_INLINE_TWIST_INVERTED=49
TRACK_QUARTER_LOOP_UNINVERTED=50
TRACK_QUARTER_LOOP_INVERTED=51
TRACK_RAPIDS=52
TRACK_HALF_LOOP_UNINVERTED=53
TRACK_HALF_LOOP_INVERTED=54

TRACK_WATERFALL=55
TRACK_WHIRLPOOL=56
TRACK_BRAKE_FOR_DROP=57
TRACK_CORKSCREW_UNINVERTED=58
TRACK_CORKSCREW_INVERTED=59
TRACK_HEARTLINE_TRANSFER=60
TRACK_MINI_GOLF_HOLE=61
TRACK_ROTATION_CONTROL_TOGGLE=62
TRACK_SLOPE_STEEP_UP=63

TRACK_GROUP_COUNT=64

TRACK_ELEM_FLAG_ONLY_UNDERWATER = (1 << 0)
TRACK_ELEM_FLAG_TURN_LEFT = (1 << 1)
TRACK_ELEM_FLAG_TURN_RIGHT = (1 << 2)
TRACK_ELEM_FLAG_TURN_BANKED = (1 << 3)
TRACK_ELEM_FLAG_TURN_SLOPED = (1 << 4)
TRACK_ELEM_FLAG_DOWN = (1 << 5)
TRACK_ELEM_FLAG_UP = (1 << 6)
TRACK_ELEM_FLAG_NORMAL_TO_INVERSION = (1 << 7)
TRACK_ELEM_FLAG_IS_GOLF_HOLE = (1 << 7)
TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT = (1 << 8)
TRACK_ELEM_FLAG_ONLY_ABOVE_GROUND = (1 << 9)
TRACK_ELEM_FLAG_IS_STEEP_UP = (1 << 10)
TRACK_ELEM_FLAG_HELIX = (1 << 11)
TRACK_ELEM_FLAG_ALLOW_LIFT_HILL = (1 << 12)
TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT = (1 << 13)
TRACK_ELEM_FLAG_INVERSION_TO_NORMAL = (1 << 14)
TRACK_ELEM_FLAG_BANKED = (1 << 15)

TRACK_FLAGS = [
       TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       0,
       0,
       0,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_IS_STEEP_UP | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_IS_STEEP_UP | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_IS_STEEP_UP | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_TURN_LEFT,
       TRACK_ELEM_FLAG_TURN_RIGHT,
       TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_BANKED | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_BANKED | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
       0,
       0,
       TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_TURN_LEFT,
       TRACK_ELEM_FLAG_TURN_RIGHT,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_BANKED | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_BANKED | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
       TRACK_ELEM_FLAG_TURN_LEFT,
       TRACK_ELEM_FLAG_TURN_RIGHT,
       TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_IS_STEEP_UP | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_IS_STEEP_UP | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       0,
       0,
       0,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_UP,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_DOWN,
       TRACK_ELEM_FLAG_TURN_LEFT,
       TRACK_ELEM_FLAG_TURN_RIGHT,
       0,
       0,
       TRACK_ELEM_FLAG_TURN_LEFT,
       TRACK_ELEM_FLAG_TURN_RIGHT,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_HELIX | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_HELIX | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_HELIX | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_HELIX | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_HELIX | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_HELIX | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_HELIX | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_HELIX | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       0,
       0,
       TRACK_ELEM_FLAG_ONLY_ABOVE_GROUND,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_HELIX | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_HELIX | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_HELIX | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_HELIX | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_HELIX,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_HELIX,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_HELIX,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_HELIX,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       0,
       0,
       0,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       0,
       TRACK_ELEM_FLAG_UP,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       0,
       TRACK_ELEM_FLAG_DOWN,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
     TRACK_ELEM_FLAG_UP,
     TRACK_ELEM_FLAG_UP,
       TRACK_ELEM_FLAG_UP,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP,
       TRACK_ELEM_FLAG_DOWN,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_TURN_LEFT,
       TRACK_ELEM_FLAG_TURN_RIGHT,
       TRACK_ELEM_FLAG_TURN_LEFT,
       TRACK_ELEM_FLAG_TURN_RIGHT,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_BANKED | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_BANKED | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_BANKED | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_BANKED | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_IS_STEEP_UP | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_IS_STEEP_UP | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_IS_STEEP_UP | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_IS_STEEP_UP | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_IS_STEEP_UP | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL,
       TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN,
       TRACK_ELEM_FLAG_DOWN,
       TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       0,
       0,
       TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_IS_GOLF_HOLE,
       TRACK_ELEM_FLAG_IS_GOLF_HOLE,
       TRACK_ELEM_FLAG_IS_GOLF_HOLE,
       TRACK_ELEM_FLAG_IS_GOLF_HOLE,
       TRACK_ELEM_FLAG_IS_GOLF_HOLE,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_UP,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_UP,
       0,
       0,
       0,
       TRACK_ELEM_FLAG_DOWN,
       TRACK_ELEM_FLAG_DOWN,
       0,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_BANKED,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP,
       TRACK_ELEM_FLAG_TURN_LEFT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN,
       TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       TRACK_ELEM_FLAG_UP | TRACK_ELEM_FLAG_NORMAL_TO_INVERSION | TRACK_ELEM_FLAG_INVERSION_TO_NORMAL,
       0,
       0,
       0,
       0,
       TRACK_ELEM_FLAG_ONLY_ABOVE_GROUND,
       0,
       0,
       0,
       0,
       0,
       0,
]

VEHICLE_UPDATE_MOTION_TRACK_FLAG_VEHICLE_AT_STATION = 1 << 0
VEHICLE_UPDATE_MOTION_TRACK_FLAG_1 = 1 << 1
VEHICLE_UPDATE_MOTION_TRACK_FLAG_2 = 1 << 2
VEHICLE_UPDATE_MOTION_TRACK_FLAG_3 = 1 << 3
VEHICLE_UPDATE_MOTION_TRACK_FLAG_VEHICLE_ON_LIFT_HILL = 1 << 4
VEHICLE_UPDATE_MOTION_TRACK_FLAG_5 = 1 << 5
VEHICLE_UPDATE_MOTION_TRACK_FLAG_VEHICLE_DERAILED = 1 << 6
VEHICLE_UPDATE_MOTION_TRACK_FLAG_VEHICLE_COLLISION = 1 << 7
VEHICLE_UPDATE_MOTION_TRACK_FLAG_8 = 1 << 8
VEHICLE_UPDATE_MOTION_TRACK_FLAG_9 = 1 << 9
VEHICLE_UPDATE_MOTION_TRACK_FLAG_VEHICLE_AT_BLOCK_BRAKE = 1 << 10
VEHICLE_UPDATE_MOTION_TRACK_FLAG_11 = 1 << 11
VEHICLE_UPDATE_MOTION_TRACK_FLAG_12 = 1 << 12

VEHICLE_UPDATE_FLAG_ON_LIFT_HILL = (1 << 0),

STATUS_MOVINGTOENDOFSTATION = 1
STATUS_DEPARTING = 2
STATUS_TRAVELLING = 3
STATUS_ARRIVING = 4


RIDE_TESTING_SHELTERED = 1 << 0
RIDE_TESTING_TURN_LEFT = 1 << 1
RIDE_TESTING_TURN_RIGHT = 1 << 2
RIDE_TESTING_TURN_BANKED = 1 << 3
RIDE_TESTING_TURN_SLOPED = 1 << 4
RIDE_TESTING_DROP_DOWN = 1 << 5
RIDE_TESTING_POWERED_LIFT = 1 << 6
RIDE_TESTING_DROP_UP = 1 << 7

CURRENT_TURN_COUNT_MASK = 0xF800
TURN_MASK_1_ELEMENT = 0x001F
TURN_MASK_2_ELEMENTS = 0x00E0
TURN_MASK_3_ELEMENTS = 0x0700
TURN_MASK_4_PLUS_ELEMENTS = 0xF800

PROXIMITY_WATER_OVER = 0                    
PROXIMITY_WATER_TOUCH = 1                  
PROXIMITY_WATER_LOW = 2                    
PROXIMITY_WATER_HIGH = 3                   
PROXIMITY_SURFACE_TOUCH = 4                
PROXIMITY_QUEUE_PATH_OVER = 5              
PROXIMITY_QUEUE_PATH_TOUCH_ABOVE = 6       
PROXIMITY_QUEUE_PATH_TOUCH_UNDER = 7      
PROXIMITY_PATH_TOUCH_ABOVE = 8              
PROXIMITY_PATH_TOUCH_UNDER = 9             
PROXIMITY_OWN_TRACK_TOUCH_ABOVE = 10         
PROXIMITY_OWN_TRACK_CLOSE_ABOVE = 11      
PROXIMITY_FOREIGN_TRACK_ABOVE_OR_BELOW = 12  
PROXIMITY_FOREIGN_TRACK_TOUCH_ABOVE = 13    
PROXIMITY_FOREIGN_TRACK_CLOSE_ABOVE = 14    
PROXIMITY_SCENERY_SIDE_BELOW = 15           
PROXIMITY_SCENERY_SIDE_ABOVE = 16           
PROXIMITY_OWN_STATION_TOUCH_ABOVE = 17      
PROXIMITY_OWN_STATION_CLOSE_ABOVE = 18      
PROXIMITY_TRACK_THROUGH_VERTICAL_LOOP = 19   
PROXIMITY_PATH_TROUGH_VERTICAL_LOOP = 20    
PROXIMITY_INTERSECTING_VERTICAL_LOOP = 21   
PROXIMITY_THROUGH_VERTICAL_LOOP = 22        
PROXIMITY_PATH_SIDE_CLOSE = 23              
PROXIMITY_FOREIGN_TRACK_SIDE_CLOSE = 24     
PROXIMITY_SURFACE_SIDE_CLOSE = 25           
PROXIMITY_COUNT = 26

RIDE_ELEMENT_TUNNEL_SPLASH_OR_RAPIDS = 1 << 5